authentication/urls.py
from django.urls import path
from authentication.views.auth.views import *
from authentication.views.user.views import *
from authentication.views.dashboard.views import *

app_name= 'authentication'

urlpatterns = [
  path('login/', LoginFormView.as_view(), name='login'),
  path('logout/', LogoutView.as_view(), name='logout'), 
  path('user/', UserListView.as_view(), name='user'),
  path('user/create/',UserCreateView.as_view(), name='user_create'),
  path('user/<int:pk>/edit/',UserUpdateView.as_view(), name='user_edit'),
  path('dashboard/',DashboardTemplateView.as_view(),name='dashboard')
]

misitio/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('request.urls'))
]

request/urls.py
from django.urls import path
from django.shortcuts import redirect
from request.views.patient.views import PatientListView, PatientCreateView, PatientUpdateView
from request.views.mhouse.views import MedicalHouseListView, MedicalHouseCreateView, MedicalHouseUpdateView
from request.views.material.views import MaterialSelectView, MaterialListView, MaterialCreateView, MaterialUpdateView
from request.views.prequest.views import *
from request.views.uptake.views import *
from request.views.entry.views import EntryListView, EntryCreateView, EntryDeleteView
from request.views.report.views import PreRequestPdfView, UptakePdfView

app_name= 'request'

urlpatterns=[
    path('', lambda req: redirect('/auth/dashboard/'),name='dashboard'),
    path('patient/',PatientListView.as_view(),name='patient'),
    path('patient/create/',PatientCreateView.as_view(),name='patient_create'),
    path('patient/<int:pk>/edit/',PatientUpdateView.as_view(),name='patient_edit'),
    path('mhouse/',MedicalHouseListView.as_view(),name='mhouse'),
    path('mhouse/create/',MedicalHouseCreateView.as_view(),name='mhouse_create'),
    path('mhouse/<int:pk>/edit/',MedicalHouseUpdateView.as_view(),name='mhouse_edit'),
    path('prerequest/',PreRequestListView.as_view(),name='prerequest'),
    path('prerequest/create/',PreRequestCreateView.as_view(),name='prerequest_create'),
    path('prerequest/<int:pk>/edit/',PreRequestUpdateView.as_view(),name="prerequest_edit"),
    path('prerequest/<int:pk>/format/',PreRequestPdfView.as_view(),name="prerequest_format"),
    path('prerequest/<int:pk>/validate/',PreRequestValidateView.as_view(),name='prerequest_validate'),
    path('prerequest/<int:pk>/store/',PreRequestStoreView.as_view(),name="prerequest_store"),
    path('prerequest/<int:pk>/shopping/',PreRequestShoppingView.as_view(),name="prerequest_shopping"),
    path('prerequest/<int:pk>/receive/',PreRequestReceiveView.as_view(),name="prerequest_receive"),
    path('prerequest/<int:pk>/delete/',PreRequestAbortingView.as_view(),name='prerequest_delete'),
    path('prerequest/<int:pk>/decline/',PreRequestDeclineView.as_view(),name='prerequest_decline'),
    path('uptake/',UptakeListView.as_view(),name='uptake'),
    path('uptake/<int:pk>/',UptakeCreateView.as_view(),name='uptake_create'),
    path('uptake/<int:pk>/format/',UptakePdfView.as_view(),name="uptake_format"),
    path('uptake/<int:pk>/validate/',UptakeValidateView.as_view(),name="uptake_validate"),
    path('uptake/<int:pk>/store/',UptakeStoreView.as_view(),name="uptake_store"),
    path('uptake/<int:pk>/shopping/',UptakeShoppingView.as_view(),name="uptake_shopping"),
    path('uptake/<int:pk>/paid/',UptakePaidView.as_view(),name="uptake_paid"),
    path('entry/',EntryListView.as_view(),name='entry'),
    path('entry/create/',EntryCreateView.as_view(),name='entry_create'),
    path('entry/<int:pk>/inactive/',EntryDeleteView.as_view(),name='entry_inactive'),
    path('material/',MaterialListView.as_view(),name='material'),
    path('material/create/',MaterialCreateView.as_view(),name='material_create'),
    path('material/<int:pk>/edit/',MaterialUpdateView.as_view(),name='material_edit'),
    path('material/select/',MaterialSelectView.as_view(),name='material_select')
]

request/views/entry/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpRequest, HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.db import transaction
from request.forms import *
from request.models import *
from django.urls import reverse_lazy
from datetime import datetime

class EntryListView(LoginRequiredMixin,ListView):
  model = Entry
  template_name = "entry/index.html"

  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)
  
  def get_queryset(self):
    return Lot.objects.all().order_by('-pk')

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Ingresos'
    context["minventory"] = 'menu-open'
    context["entry"] = 'active'
    return context
  
class EntryCreateView(LoginRequiredMixin,CreateView):
  model = Entry
  form_class = EntryForm
  template_name = "entry/create.html"

  def get_success_url(self):
    messages.success(self.request, '¡Ingreso creado con éxito!')
    return reverse_lazy('request:entry')
  
  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)
  
  def generate_code(self):
    ident = 'IN'
    if Entry.objects.count() > 0:
      next_code = Entry.objects.latest('id').id + 1
      next_code = str(next_code)
      next_code.zfill(3)
    else:
      next_code = '1'
      next_code.zfill(3)
    return "{}-{}".format(ident,next_code)
  
  def post(self, request, *args, **kwargs):
    try:
      with transaction.atomic():
        get_house = MedicalHouse.objects.get(pk=request.POST['house'])
        # add new pre request
        new_entry = Entry.objects.create(
          code = self.generate_code(),
          house = get_house,
          date_award = request.POST['date_award'],
          nog = request.POST['nog'],
          siaf = request.POST['siaf'],
          ppr = request.POST['ppr'],
          comment = request.POST['comment'],
          user = self.request.user,
        )
        new_entry.save()
        
        get_material = request.POST.getlist('material_id[]')
        get_price_purchase = request.POST.getlist('price_purchase[]')
        get_ammount = request.POST.getlist('ammount[]')
        get_subtotal = request.POST.getlist('subtotal[]')
        
        total = 0
        it = 0
        for ref in get_material:
          product_price_purchase = get_price_purchase[it]
          temp_subtotal = float(product_price_purchase) * float(get_ammount[it])
          total += temp_subtotal
          it += 1
        new_entry.total=total
        new_entry.save()

        i = 0
        for item in get_material:
          material = Material.objects.get(pk=item)
          get_status_material_active = Status.objects.get(pk=6)
          new_detail = EntryDetail.objects.create(
            entry = new_entry,
            ammount = get_ammount[i],
            price_purchase = format(float(get_price_purchase[i]),'.2f'),
            subtotal = format(float(get_subtotal[i]),'.2f'),
            material = material
          )
          new_detail.save()
          new_detail.material.stock += float(new_detail.ammount)
          new_detail.material.status = get_status_material_active
          new_detail.material.save()
          new_lot = Lot.objects.create(
            stock = get_ammount[i],
            entry_detail = new_detail
          )
          new_lot.save()
          i += 1

    except Exception as e:
      messages.error(self.request,str(e))
      return HttpResponseRedirect('request:prerequest_create')
    return HttpResponseRedirect(self.get_success_url())
    
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Nuevo ingreso'
    context["minventory"] = 'menu-open'
    context["entry"] = 'active'
    return context


class EntryDeleteView(LoginRequiredMixin,DeleteView):
  model = Entry
  template_name = "entry/inactive.html"

  def get_success_url(self):
    messages.success(self.request, '¡Ingreso inactivo!')
    return reverse_lazy('request:entry')
  
  def post(self, request, *args, **kwargs):
    try:
      entry = self.get_object()
      lots = Lot.objects.filter(entry_detail__entry__id=entry.pk)
      for item in lots:
        lot = Lot.objects.get(pk=item.pk)
        new_status = Status.objects.get(pk=20)
        lot.status = new_status
        lot.save()
      new_entry_status = Status.objects.get(pk=17)
      entry_update = Entry.objects.get(pk=entry.pk)
      entry_update.status = new_entry_status
      entry_update.save()
    except Exception as e:
      messages.error(self.request,str(e))
      return HttpResponseRedirect('request:entry')
    return HttpResponseRedirect(self.get_success_url())
  
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Inactivar ingreso'
    return context

request/views/material/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, ListView, CreateView, UpdateView
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib import messages
from django.db.models import Q
from request.models import *
from request.forms import *
from django.urls import reverse_lazy

class MaterialListView(LoginRequiredMixin,ListView):
  model = Material
  template_name = "material/index.html"

  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Materiales'
    context["minventory"] = 'menu-open'
    context["material"] = 'active'
    return context
  
class MaterialCreateView(CreateView):
  model = Material
  form_class = MaterialForm
  template_name = "material/create.html"

  def get_success_url(self):
    messages.success(self.request, '¡Material agregado con éxito!')
    return reverse_lazy('request:material')
  
  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)
    
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Nuevo material'
    return context

class MaterialSelectView(LoginRequiredMixin,View):
  def get(self, request, *args, **kwargs):
    data = list()
    action = request.GET.get('action')
    if action == 'search':
      term=request.GET.get('q')
      materials=Material.objects.filter(Q(code__icontains=term) | Q(name__icontains=term) | Q(description__icontains=term))
      lots=Lot.objects.filter(Q(entry_detail__material__code__icontains=term) | Q(entry_detail__material__name__icontains=term) | 
        Q(entry_detail__material__description__icontains=term)).filter(stock__gt=0).filter(status__id=19)
      for item in materials:
        lot = next(filter(lambda material:material.entry_detail.material.id == int(item.pk), lots), None)
        print(lot)
        if lot is None:
          datos={
            'type':'list',
            'id':item.id,
            'code':item.code,
            'name':item.name,
            'description':item.description,
          }
          data.append(datos)
        else:
          lotsearch = Lot.objects.filter(entry_detail__material__id=item.pk).filter(status__id=19)
          for lot in lotsearch:
            datos={
              'type':'stock',
              'id':lot.id,
              'code':lot.entry_detail.material.code,
              'name':lot.entry_detail.material.name,
              'description':lot.entry_detail.material.description,
              'stock':lot.stock,
              'house':lot.entry_detail.entry.house.id,
              'mhouse': "{} - {}".format(lot.entry_detail.entry.house.nit,lot.entry_detail.entry.house.name)
            }  
            data.append(datos)
    elif action == 'select':
      lot_id = 0
      type_model = request.GET.get('type')
      if type_model == 'stock':
        lot = Lot.objects.get(pk=request.GET.get('id'))
        data.append({
          'type':'stock',
          'id':lot.id,
          'code':lot.entry_detail.material.code,
          'name':lot.entry_detail.material.name,
          'description':lot.entry_detail.material.description,
          'stock':lot.stock,
          'house':lot.entry_detail.entry.house.id,
          'mhouse': "{} - {}".format(lot.entry_detail.entry.house.nit,lot.entry_detail.entry.house.name)
        })
      else:
        material = Material.objects.get(pk = request.GET.get('id'))
        data.append({
          'id' : material.id,
          'code' : material.code,
          'name':material.name,
          'description' : material.description,
        })
    elif action == 'search_entry':
      term=request.GET.get('q')
      materials=Material.objects.filter(Q(code__icontains=term) | Q(name__icontains=term) | Q(description__icontains=term))
      for item in materials:
        datos={
          'type':'list',
          'id':item.id,
          'code':item.code,
          'name':item.name,
          'description':item.description,
        }
        data.append(datos)
    return JsonResponse(data,safe=False)
  
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Material'
    return context

class MaterialUpdateView(LoginRequiredMixin,UpdateView):
  model = Material
  form_class = MaterialForm
  template_name = "material/edit.html"

  def get_success_url(self):
    messages.success(self.request, '¡Material editado con éxito!')
    return reverse_lazy('request:material')
  
  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)
  
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Editar material'
    return context

request/views/mhouse/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpRequest, HttpResponse
from django.views.generic import ListView, CreateView, UpdateView
from request.forms import *
from request.models import *
from django.urls import reverse_lazy

class MedicalHouseListView(ListView):
  model = MedicalHouse
  template_name = "mhouse/index.html"

  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)
  
  def get_queryset(self):
    return MedicalHouse.objects.all().order_by('-pk')

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Casa médica'
    context["madmins"] = 'menu-open'
    context["mhouse"] = 'active'
    return context

class MedicalHouseCreateView(CreateView):
  model = MedicalHouse
  form_class = MedicalHouseForm
  template_name = "mhouse/create.html"
  
  def get_success_url(self):
    messages.success(self.request, '¡Casa médica agregada con éxito!')
    return reverse_lazy('request:mhouse')
  
  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)
    
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Nueva casa médica'
    return context

class MedicalHouseUpdateView(UpdateView):
  model = MedicalHouse
  form_class = MedicalHouseForm
  template_name = "mhouse/edit.html"

  def get_success_url(self):
    messages.success(self.request, '¡Registro editado con éxito!')
    return reverse_lazy('request:mhouse')
  
  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)
    
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Editar registro de casa médica'
    return context

request/templates/uptake/create.html
{% extends 'admin.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Consumo de materiales</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'authentication:dashboard' %}">Tablero</a></li>
            <li class="breadcrumb-item"><a href="{% url 'request:prerequest' %}">Consumo de materiales</a></li>
            <li class="breadcrumb-item active">Consumo de materiales</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
  <section class="content">
    <div class="container-fluid">
      <form action="{% url 'request:uptake_create' prerequest.pk %}" method="post" >
        {% csrf_token %}
        <div class="row">
          <section class="col-md-12">
            <div class="card card-outline card-success">
              <div class="card-header">
                <h3 class="card-title">CONSUMO DE PRESOLICITUD</h3>
              </div>
              <div class="card-body">
                <div class="row">
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="pnumber">No. de pre solicitud</label>
                      <input type="text" class="form-control" readonly value="{{prerequest.number}}">
                      <input type="hidden" name="prequest_id" value="{{prerequest.pk}}">
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="pmembership">No. de afiliación</label>
                      <input type="text" class="form-control" readonly value="{{prerequest.patient.membership}}">
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="pnamepatient">Nombres y Apellidos del paciente</label>
                      <input type="text" class="form-control" readonly value="{{prerequest.patient.first_name}} {{prerequest.patient.last_name}}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="pdiagnosis">Diagnóstico</label>
                      <input type="text" class="form-control" readonly value="{{prerequest.diagnosis}}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="pprocedure">Procedimiento</label>
                      <input type="text" class="form-control" readonly value="{{prerequest.procedure}}">
                    </div>
                  </div>
                </div>
                <hr>
                <div class="row">
                  {% for field in form.visible_fields %}
                    {% if field.name == 'house' %}
                      <div class="col-md-4">
                        <div class="form-group">
                          <label for="{{ field.name }}">{{ field.label }}</label>
                          <input type="hidden" id="house_select" name="house" value="{{ prerequest.house.pk }}">
                          {{ field }}
                        </div>
                      </div>
                    {% else %}
                      <div class="col-md-3">
                        <div class="form-group">
                          <label for="{{ field.name }}">{{ field.label }}</label>
                          {{ field }}
                        </div>
                      </div>
                    {% endif %}
                  {% endfor %}
                </div>
            </div>
          </section>
          <section class="col-md-12">
            <div class="card card-outline card-info">
              <div class="card-header">
                <h5 class="card-title">DETALLE DE CONSUMO</h5>
              </div>
              <div class="card-body" id="detail_entry">
                <table id="det_uptake" class="table table-bordered table-striped" style="width:100%;">
                  <thead>
                    <tr>
                      <th width="10%">opciones</th>
                      <th>Material</th>
                      <th width="10%">Cantidad</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% if prerequest.stock %}
                      {% for item in prdetail %}
                        <tr>
                          <td>
                            <button class="btn btn-danger deleteItem" title="Eliminar"> <i class="fas fa-times"></i> </button>
                          </td>
                          <td>
                            <input type="hidden" name="material_id[]" id="material_id" value="{{ item.lot.entry_detail.material.pk }}">
                            {{ item.lot.entry_detail.material.code }} // {{ item.lot.entry_detail.material.name }} - {{ item.lot.entry_detail.material.description }}
                          </td>
                          <td>
                            <input type="number" style="text-align: center;" class="form-control" name="amount[]" id="amount" value="0" max="{{ item.amount }}" onchange="validateRows();">
                          </td>
                        </tr>
                      {% endfor %}
                    {% else %}
                      {% for item in prdetail %}
                      <tr>
                        <td>
                          <button class="btn btn-danger deleteItem" title="Eliminar"> <i class="fas fa-times"></i> </button>
                        </td>
                        <td>
                          <input type="hidden" name="material_id[]" id="material_id" value="{{ item.material.pk }}">`
                          {{ item.material.code }} / {{ item.material.name }} - {{ item.material.description }}
                        </td>
                        <td>
                          <input type="number" style="text-align: center;" class="form-control" name="amount[]" id="amount" min="0" value="0" max="{{ item.amount }}" onchange="validateRows();">
                        </td>
                      </tr>
                      {% endfor %}
                    {% endif %}
                  </tbody>
                  <tfoot>
                    <tr>
                      <th colspan="2" style="text-align: right;">TOTAL MATERIALES</th>
                      <th>
                        <input type="number" id="total" style="text-align: center;" class="form-control total_material" min="0" value="0" readonly>
                      </th>
                    </tr>
                  </tfoot>
                </table>
              </div>
              <div class="card-footer" id="actions">
                <button type="button" class="btn btn-danger"><i class="fas fa-times"></i> CANCELAR </button>
                <button type="submit" class="btn btn-primary float-right"><i class="fas fa-check"></i> GUARDAR  </button>
              </div>
            </div>
          </section>
        </div>
      </form>
    </div>
  </section>
{% endblock content %}

{% block scripts %}
  <script src="{% static 'assets/js/resources/uptake.js' %}"></script>
{% endblock %}

request/templates/uptake/index.html
{% extends 'admin.html' %}

{% block content %}
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0" id="titleview">Hoja de consumo</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'authentication:dashboard' %}">Tablero</a></li>
            <li class="breadcrumb-item active">Hoja de consumo</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Listado de hojas de consumo</h5>
            </div>
            <div class="card-body">
              <table id="lists" class="table table-bordered table-hover table-striped" style="width:100%">
                <thead>
                  <tr>
                    <th>Número</th>
                    <th>Pre solicitud</th>
                    <th>Fecha</th>
                    <th>Encargado</th>
                    <th>Estado</th>
                    <th>Opciones</th>
                  </tr>
                </thead>
                <tbody>
                  {% for item in object_list %}
                    <tr>
                      <td>{{ item.number }}</td>
                      <td>{{ item.pre_request.number }}</td>
                      <td>{{ item.date }}</td>     
                      <td>{{ item.user.username }}</td>
                      <td>{{ item.status.name }}</td>
                      <td class="text-center">
                        {% comment %} <button class="btn btn-info" onclick="viewSellDetail({{ item.id }});"><i class="fas fa-eye"></i></button> {% endcomment %}
                        <a class="btn btn-warning popup" href="{% url 'request:uptake_format' item.id %}" target="blank">
                          <span class="popuptext">Imprimir hoja de consumo</span>
                          <i class="fas fa-print"></i>
                        </a>
                        {% comment %} <a class="btn btn-ligth bg-teal popup" href="{% url 'request:uptake_create' item.id %}" target="blank">
                          <span class="popuptext">Consumir</span>
                          <i class="fas fa-file-download"></i>
                        </a> {% endcomment %}
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

request/templates/uptake/validate.html
<div class="modal-dialog modal-xl modal-dialog-centered">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title">Valide los datos ingresados</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <form action="{{ option }}" method="get">
      <div class="modal-body">
        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <label>No. de pre solicitud</label>
              <input type="text" id="v_prerequest" value="{{ prequest.number }}" readonly class="form-control form-control-border"/>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <label>No. quirófano</label>
              <input type="text" id="v_operating_room" value="{{ uptake.operating_room }}" readonly class="form-control form-control-border"/>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <label>No. de hoja</label>
              <input type="text" id="v_uptake" value="{{ uptake.number }}" readonly class="form-control form-control-border"/>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label>Paciente</label>
              <input type="text" id="v_patient" value="{{ prequest.patient }}" readonly class="form-control form-control-border"/>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label>Diagnóstico</label>
              <input type="text" id="v_diagnosis" value="{{ prequest.diagnosis }}" readonly class="form-control form-control-border"/>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <label>Procedimiento</label>
              <input type="text" id="v_procedure" value="{{ prequest.procedure }}" readonly class="form-control form-control-border"/>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <label>Cirujano</label>
              <input type="text" id="v_surgeon" value="{{ uptake.surgeon }}" readonly class="form-control form-control-border"/>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <label>Instrumentista</label>
              <input type="text" id="v_instrumentalist" value="{{ uptake.instrumentalist }}" readonly class="form-control form-control-border"/>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <label>Circulante</label>
              <input type="text" id="v_circulating" value="{{ uptake.circulating }}" readonly class="form-control form-control-border"/>
            </div>
          </div>
        </div>
        <hr />
        <label>Material(es)</label>
        <table id="v_details" class="table table-bordered table-striped" style="width:100%">
          <thead>
            <tr>
              <th>Material</th>
              <th>Cantidad</th>
            </tr>
          </thead>
          <tbody>
          {% for item in detail %}
            <tr>
              <td>{{ item.material.code }} / {{ item.material.name }} - {{ item.material.description }}</td>
              <td>{{ item.amount }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
        
        {% if more %}
          <div class="col-md-4">
            <div class="form-group">
              <label for="number_siaf">Número de SIAF</label>
              <input type="text" id="number_siaf" name="number_siaf" placeholder="Ingrese el número de SIAF" required class="form-control"/>
            </div>
          </div>
        {% endif %}
      </div>
      <div class="modal-footer justify-content-between">
        <button type="button" class="btn btn btn-danger"><i class="fas fa-times"></i> CANCELAR </button>
        <button type="submit" class="btn btn btn-primary" id="btn-validate-prequest"><i class="fas fa-save"></i> CONFIRMAR </button>
      </div>
    </form>
  </div>
</div>