authentication/urls.py
from django.urls import path
from authentication.views.auth.views import *
from authentication.views.user.views import *
from authentication.views.dashboard.views import *

app_name= 'authentication'

urlpatterns = [
  path('login/', LoginFormView.as_view(), name='login'),
  path('logout/', LogoutView.as_view(), name='logout'), 
  path('user/', UserListView.as_view(), name='user'),
  path('user/create/',UserCreateView.as_view(), name='user_create'),
  path('user/<int:pk>/edit/',UserUpdateView.as_view(), name='user_edit'),
  path('dashboard/',DashboardTemplateView.as_view(),name='dashboard')
]

misitio/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('request.urls'))
]

request/urls.py
from django.urls import path
from django.shortcuts import redirect
from request.views.patient.views import PatientListView, PatientCreateView, PatientUpdateView
from request.views.mhouse.views import MedicalHouseListView, MedicalHouseCreateView, MedicalHouseUpdateView
from request.views.material.views import MaterialSelectView, MaterialListView, MaterialCreateView, MaterialUpdateView
from request.views.prequest.views import *
from request.views.uptake.views import *
from request.views.entry.views import EntryListView, EntryCreateView, EntryDeleteView
from request.views.report.views import PreRequestPdfView, UptakePdfView

app_name= 'request'

urlpatterns=[
    path('', lambda req: redirect('/auth/dashboard/'),name='dashboard'),
    path('patient/',PatientListView.as_view(),name='patient'),
    path('patient/create/',PatientCreateView.as_view(),name='patient_create'),
    path('patient/<int:pk>/edit/',PatientUpdateView.as_view(),name='patient_edit'),
    path('mhouse/',MedicalHouseListView.as_view(),name='mhouse'),
    path('mhouse/create/',MedicalHouseCreateView.as_view(),name='mhouse_create'),
    path('mhouse/<int:pk>/edit/',MedicalHouseUpdateView.as_view(),name='mhouse_edit'),
    path('prerequest/',PreRequestListView.as_view(),name='prerequest'),
    path('prerequest/create/',PreRequestCreateView.as_view(),name='prerequest_create'),
    path('prerequest/<int:pk>/edit/',PreRequestUpdateView.as_view(),name="prerequest_edit"),
    path('prerequest/<int:pk>/format/',PreRequestPdfView.as_view(),name="prerequest_format"),
    path('prerequest/<int:pk>/validate/',PreRequestValidateView.as_view(),name='prerequest_validate'),
    path('prerequest/<int:pk>/store/',PreRequestStoreView.as_view(),name="prerequest_store"),
    path('prerequest/<int:pk>/shopping/',PreRequestShoppingView.as_view(),name="prerequest_shopping"),
    path('prerequest/<int:pk>/receive/',PreRequestReceiveView.as_view(),name="prerequest_receive"),
    path('prerequest/<int:pk>/delete/',PreRequestAbortingView.as_view(),name='prerequest_delete'),
    path('prerequest/<int:pk>/decline/',PreRequestDeclineView.as_view(),name='prerequest_decline'),
    path('uptake/',UptakeListView.as_view(),name='uptake'),
    path('uptake/<int:pk>/',UptakeCreateView.as_view(),name='uptake_create'),
    path('uptake/<int:pk>/format/',UptakePdfView.as_view(),name="uptake_format"),
    path('uptake/<int:pk>/validate/',UptakeValidateView.as_view(),name="uptake_validate"),
    path('uptake/<int:pk>/store/',UptakeStoreView.as_view(),name="uptake_store"),
    path('uptake/<int:pk>/shopping/',UptakeShoppingView.as_view(),name="uptake_shopping"),
    path('uptake/<int:pk>/paid/',UptakePaidView.as_view(),name="uptake_paid"),
    path('entry/',EntryListView.as_view(),name='entry'),
    path('entry/create/',EntryCreateView.as_view(),name='entry_create'),
    path('entry/<int:pk>/inactive/',EntryDeleteView.as_view(),name='entry_inactive'),
    path('material/',MaterialListView.as_view(),name='material'),
    path('material/create/',MaterialCreateView.as_view(),name='material_create'),
    path('material/<int:pk>/edit/',MaterialUpdateView.as_view(),name='material_edit'),
    path('material/select/',MaterialSelectView.as_view(),name='material_select')
]

templates/layouts/footer.html
<!-- Main Footer -->
<footer class="main-footer">
    <strong>Copyright &copy; 2023 <a href="/dashboard/">OSTEO</a>.</strong>
    Todos los derechos reservados
    <div class="float-right d-none d-sm-inline-block">
      <b>Versión</b> 1.1.0
    </div>
  </footer>

templates/layouts/navbar.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"
        ><i class="fas fa-bars"></i
      ></a>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> 4 new messages
          <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-file mr-2"></i> 3 new reports
          <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer"
          >See All Notifications</a
        >
      </div>
    </li>
    {% if request.user.is_authenticated %}
    <li class="nav-item dropdown user-menu">
      <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
        <img
          src="{% static 'assets/images/defaultuser.png' %}"
          class="user-image img-circle elevation-2"
          alt="User Image"
        />
        <span class="d-none d-md-inline"
          >{{ request.user.first_name }} {{ request.user.last_name }}</span
        >
      </a>
      <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <li class="user-header bg-navy">
          <img
            src="{% static 'assets/images/defaultuser.png' %}"
            class="img-circle elevation-2"
            alt="User Image"
          />
          <p>
            {{ request.user.first_name }} {{ request.user.last_name }}
            <small>{{ request.user.groups.all.0.name }}</small>
          </p>
        </li>
        <li class="user-footer">
          <form action="{% url 'authentication:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-flat">
              <i class="fas fa-sign-out-alt"></i> Salir
            </button>
          </form>
        </li>
      </ul>
    </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link" data-widget="fullscreen" href="#" role="button">
        <i class="fas fa-expand-arrows-alt"></i>
      </a>
    </li>
  </ul>
</nav>

templates/layouts/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-navy elevation-3">
  <a href="/dashboard/" class="brand-link bg-navy">
    <img src="{% static 'assets/images/logo.png' %}" alt="IGSS Logo" class="brand-image img-circle elevation-3" style="background-color:white;">
    <span class="brand-text font-bold-light"><b>O</b>STEOSÍNTESIS</span>
  </a>
  <hr>
  <div class="sidebar">
    <div class="form-inline">
      <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar" type="search" placeholder="Buscar" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-sidebar">
            <i class="fas fa-search fa-fw"></i>
          </button>
        </div>
      </div>
    </div>
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="true">
        <li class="nav-item">
          <a href="{% url 'request:dashboard' %}" class="nav-link {{ dashboard }}">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              Tablero
            </p>
          </a>
        </li>
        <li class="nav-item {{ mprequest }}">
          <a href="#" class="nav-link {{ prequest }}">
            <i class="nav-icon fas fa-file-medical"></i>
            <p>
              Pre solicitud
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'request:prerequest' %}" class="nav-link {{ prequest }}">
                <i class="fas fa-clipboard-list nav-icon"></i>
                <p>Listado</p>
              </a>
            </li>
          </ul>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'request:uptake' %}" class="nav-link {{ uptake }}">
                <i class="fas fa-clipboard-list nav-icon"></i>
                <p>Hojas de consumo</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item {{ minventory }}">
          <a href="#" class="nav-link {{ material }} {{ entry }}">
            <i class="nav-icon fas fa-warehouse"></i>
            <p>
              Inventario
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'request:entry' %}" class="nav-link {{ entry }}">
                <i class="fas fa-list-ul nav-icon"></i>
                <p>Ingresos</p>
              </a>
            </li>
          </ul>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'request:material' %}" class="nav-link {{ material }}">
                <i class="fas fa-briefcase-medical nav-icon"></i>
                <p>Materiales</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item {{ madmins }}">
          <a href="#" class="nav-link {{ patient }}">
            <i class="nav-icon fas fa-users-cog"></i>
            <p>
              Administrar
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'request:patient' %}" class="nav-link {{ patient }}">
                <i class="fas fa-user-injured nav-icon"></i>
                <p>Pacientes</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'request:mhouse' %}" class="nav-link {{ mhouse }}">
                <i class="fas fa-clinic-medical nav-icon"></i>
                <p>Casa médica</p>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</aside>