authentication/urls.py
from django.urls import path
from authentication.views.auth.views import *
from authentication.views.user.views import *
from authentication.views.dashboard.views import *

app_name= 'authentication'

urlpatterns = [
  path('login/', LoginFormView.as_view(), name='login'),
  path('logout/', LogoutView.as_view(), name='logout'), 
  path('user/', UserListView.as_view(), name='user'),
  path('user/create/',UserCreateView.as_view(), name='user_create'),
  path('user/<int:pk>/edit/',UserUpdateView.as_view(), name='user_edit'),
  path('dashboard/',DashboardTemplateView.as_view(),name='dashboard')
]

misitio/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('request.urls'))
]

request/urls.py
from django.urls import path
from django.shortcuts import redirect
from request.views.patient.views import PatientListView, PatientCreateView, PatientUpdateView
from request.views.mhouse.views import MedicalHouseListView, MedicalHouseCreateView, MedicalHouseUpdateView
from request.views.material.views import MaterialSelectView, MaterialListView, MaterialCreateView, MaterialUpdateView
from request.views.prequest.views import *
from request.views.uptake.views import *
from request.views.entry.views import EntryListView, EntryCreateView, EntryDeleteView
from request.views.report.views import PreRequestPdfView, UptakePdfView

app_name= 'request'

urlpatterns=[
    path('', lambda req: redirect('/auth/dashboard/'),name='dashboard'),
    path('patient/',PatientListView.as_view(),name='patient'),
    path('patient/create/',PatientCreateView.as_view(),name='patient_create'),
    path('patient/<int:pk>/edit/',PatientUpdateView.as_view(),name='patient_edit'),
    path('mhouse/',MedicalHouseListView.as_view(),name='mhouse'),
    path('mhouse/create/',MedicalHouseCreateView.as_view(),name='mhouse_create'),
    path('mhouse/<int:pk>/edit/',MedicalHouseUpdateView.as_view(),name='mhouse_edit'),
    path('prerequest/',PreRequestListView.as_view(),name='prerequest'),
    path('prerequest/create/',PreRequestCreateView.as_view(),name='prerequest_create'),
    path('prerequest/<int:pk>/edit/',PreRequestUpdateView.as_view(),name="prerequest_edit"),
    path('prerequest/<int:pk>/format/',PreRequestPdfView.as_view(),name="prerequest_format"),
    path('prerequest/<int:pk>/validate/',PreRequestValidateView.as_view(),name='prerequest_validate'),
    path('prerequest/<int:pk>/store/',PreRequestStoreView.as_view(),name="prerequest_store"),
    path('prerequest/<int:pk>/shopping/',PreRequestShoppingView.as_view(),name="prerequest_shopping"),
    path('prerequest/<int:pk>/receive/',PreRequestReceiveView.as_view(),name="prerequest_receive"),
    path('prerequest/<int:pk>/delete/',PreRequestAbortingView.as_view(),name='prerequest_delete'),
    path('prerequest/<int:pk>/decline/',PreRequestDeclineView.as_view(),name='prerequest_decline'),
    path('uptake/',UptakeListView.as_view(),name='uptake'),
    path('uptake/<int:pk>/',UptakeCreateView.as_view(),name='uptake_create'),
    path('uptake/<int:pk>/format/',UptakePdfView.as_view(),name="uptake_format"),
    path('uptake/<int:pk>/validate/',UptakeValidateView.as_view(),name="uptake_validate"),
    path('uptake/<int:pk>/store/',UptakeStoreView.as_view(),name="uptake_store"),
    path('uptake/<int:pk>/shopping/',UptakeShoppingView.as_view(),name="uptake_shopping"),
    path('uptake/<int:pk>/paid/',UptakePaidView.as_view(),name="uptake_paid"),
    path('entry/',EntryListView.as_view(),name='entry'),
    path('entry/create/',EntryCreateView.as_view(),name='entry_create'),
    path('entry/<int:pk>/inactive/',EntryDeleteView.as_view(),name='entry_inactive'),
    path('material/',MaterialListView.as_view(),name='material'),
    path('material/create/',MaterialCreateView.as_view(),name='material_create'),
    path('material/<int:pk>/edit/',MaterialUpdateView.as_view(),name='material_edit'),
    path('material/select/',MaterialSelectView.as_view(),name='material_select')
]

request/views/entry/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpRequest, HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.db import transaction
from request.forms import *
from request.models import *
from django.urls import reverse_lazy
from datetime import datetime

class EntryListView(LoginRequiredMixin,ListView):
  model = Entry
  template_name = "entry/index.html"

  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)
  
  def get_queryset(self):
    return Lot.objects.all().order_by('-pk')

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Ingresos'
    context["minventory"] = 'menu-open'
    context["entry"] = 'active'
    return context
  
class EntryCreateView(LoginRequiredMixin,CreateView):
  model = Entry
  form_class = EntryForm
  template_name = "entry/create.html"

  def get_success_url(self):
    messages.success(self.request, '¡Ingreso creado con éxito!')
    return reverse_lazy('request:entry')
  
  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)
  
  def generate_code(self):
    ident = 'IN'
    if Entry.objects.count() > 0:
      next_code = Entry.objects.latest('id').id + 1
      next_code = str(next_code)
      next_code.zfill(3)
    else:
      next_code = '1'
      next_code.zfill(3)
    return "{}-{}".format(ident,next_code)
  
  def post(self, request, *args, **kwargs):
    try:
      with transaction.atomic():
        get_house = MedicalHouse.objects.get(pk=request.POST['house'])
        # add new pre request
        new_entry = Entry.objects.create(
          code = self.generate_code(),
          house = get_house,
          date_award = request.POST['date_award'],
          nog = request.POST['nog'],
          siaf = request.POST['siaf'],
          ppr = request.POST['ppr'],
          comment = request.POST['comment'],
          user = self.request.user,
        )
        new_entry.save()
        
        get_material = request.POST.getlist('material_id[]')
        get_price_purchase = request.POST.getlist('price_purchase[]')
        get_ammount = request.POST.getlist('ammount[]')
        get_subtotal = request.POST.getlist('subtotal[]')
        
        total = 0
        it = 0
        for ref in get_material:
          product_price_purchase = get_price_purchase[it]
          temp_subtotal = float(product_price_purchase) * float(get_ammount[it])
          total += temp_subtotal
          it += 1
        new_entry.total=total
        new_entry.save()

        i = 0
        for item in get_material:
          material = Material.objects.get(pk=item)
          get_status_material_active = Status.objects.get(pk=6)
          new_detail = EntryDetail.objects.create(
            entry = new_entry,
            ammount = get_ammount[i],
            price_purchase = format(float(get_price_purchase[i]),'.2f'),
            subtotal = format(float(get_subtotal[i]),'.2f'),
            material = material
          )
          new_detail.save()
          new_detail.material.stock += float(new_detail.ammount)
          new_detail.material.status = get_status_material_active
          new_detail.material.save()
          new_lot = Lot.objects.create(
            stock = get_ammount[i],
            entry_detail = new_detail
          )
          new_lot.save()
          i += 1

    except Exception as e:
      messages.error(self.request,str(e))
      return HttpResponseRedirect('request:prerequest_create')
    return HttpResponseRedirect(self.get_success_url())
    
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Nuevo ingreso'
    context["minventory"] = 'menu-open'
    context["entry"] = 'active'
    return context


class EntryDeleteView(LoginRequiredMixin,DeleteView):
  model = Entry
  template_name = "entry/inactive.html"

  def get_success_url(self):
    messages.success(self.request, '¡Ingreso inactivo!')
    return reverse_lazy('request:entry')
  
  def post(self, request, *args, **kwargs):
    try:
      entry = self.get_object()
      lots = Lot.objects.filter(entry_detail__entry__id=entry.pk)
      for item in lots:
        lot = Lot.objects.get(pk=item.pk)
        new_status = Status.objects.get(pk=20)
        lot.status = new_status
        lot.save()
      new_entry_status = Status.objects.get(pk=17)
      entry_update = Entry.objects.get(pk=entry.pk)
      entry_update.status = new_entry_status
      entry_update.save()
    except Exception as e:
      messages.error(self.request,str(e))
      return HttpResponseRedirect('request:entry')
    return HttpResponseRedirect(self.get_success_url())
  
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Inactivar ingreso'
    return context

request/views/material/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, ListView, CreateView, UpdateView
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib import messages
from django.db.models import Q
from request.models import *
from request.forms import *
from django.urls import reverse_lazy

class MaterialListView(LoginRequiredMixin,ListView):
  model = Material
  template_name = "material/index.html"

  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Materiales'
    context["minventory"] = 'menu-open'
    context["material"] = 'active'
    return context
  
class MaterialCreateView(CreateView):
  model = Material
  form_class = MaterialForm
  template_name = "material/create.html"

  def get_success_url(self):
    messages.success(self.request, '¡Material agregado con éxito!')
    return reverse_lazy('request:material')
  
  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)
    
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Nuevo material'
    return context

class MaterialSelectView(LoginRequiredMixin,View):
  def get(self, request, *args, **kwargs):
    data = list()
    action = request.GET.get('action')
    if action == 'search':
      term=request.GET.get('q')
      materials=Material.objects.filter(Q(code__icontains=term) | Q(name__icontains=term) | Q(description__icontains=term))
      lots=Lot.objects.filter(Q(entry_detail__material__code__icontains=term) | Q(entry_detail__material__name__icontains=term) | 
        Q(entry_detail__material__description__icontains=term)).filter(stock__gt=0).filter(status__id=19)
      for item in materials:
        lot = next(filter(lambda material:material.entry_detail.material.id == int(item.pk), lots), None)
        print(lot)
        if lot is None:
          datos={
            'type':'list',
            'id':item.id,
            'code':item.code,
            'name':item.name,
            'description':item.description,
          }
          data.append(datos)
        else:
          lotsearch = Lot.objects.filter(entry_detail__material__id=item.pk).filter(status__id=19)
          for lot in lotsearch:
            datos={
              'type':'stock',
              'id':lot.id,
              'code':lot.entry_detail.material.code,
              'name':lot.entry_detail.material.name,
              'description':lot.entry_detail.material.description,
              'stock':lot.stock,
              'house':lot.entry_detail.entry.house.id,
              'mhouse': "{} - {}".format(lot.entry_detail.entry.house.nit,lot.entry_detail.entry.house.name)
            }  
            data.append(datos)
    elif action == 'select':
      lot_id = 0
      type_model = request.GET.get('type')
      if type_model == 'stock':
        lot = Lot.objects.get(pk=request.GET.get('id'))
        data.append({
          'type':'stock',
          'id':lot.id,
          'code':lot.entry_detail.material.code,
          'name':lot.entry_detail.material.name,
          'description':lot.entry_detail.material.description,
          'stock':lot.stock,
          'house':lot.entry_detail.entry.house.id,
          'mhouse': "{} - {}".format(lot.entry_detail.entry.house.nit,lot.entry_detail.entry.house.name)
        })
      else:
        material = Material.objects.get(pk = request.GET.get('id'))
        data.append({
          'id' : material.id,
          'code' : material.code,
          'name':material.name,
          'description' : material.description,
        })
    elif action == 'search_entry':
      term=request.GET.get('q')
      materials=Material.objects.filter(Q(code__icontains=term) | Q(name__icontains=term) | Q(description__icontains=term))
      for item in materials:
        datos={
          'type':'list',
          'id':item.id,
          'code':item.code,
          'name':item.name,
          'description':item.description,
        }
        data.append(datos)
    return JsonResponse(data,safe=False)
  
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Material'
    return context

class MaterialUpdateView(LoginRequiredMixin,UpdateView):
  model = Material
  form_class = MaterialForm
  template_name = "material/edit.html"

  def get_success_url(self):
    messages.success(self.request, '¡Material editado con éxito!')
    return reverse_lazy('request:material')
  
  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)
  
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Editar material'
    return context

request/views/mhouse/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpRequest, HttpResponse
from django.views.generic import ListView, CreateView, UpdateView
from request.forms import *
from request.models import *
from django.urls import reverse_lazy

class MedicalHouseListView(ListView):
  model = MedicalHouse
  template_name = "mhouse/index.html"

  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)
  
  def get_queryset(self):
    return MedicalHouse.objects.all().order_by('-pk')

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Casa médica'
    context["madmins"] = 'menu-open'
    context["mhouse"] = 'active'
    return context

class MedicalHouseCreateView(CreateView):
  model = MedicalHouse
  form_class = MedicalHouseForm
  template_name = "mhouse/create.html"
  
  def get_success_url(self):
    messages.success(self.request, '¡Casa médica agregada con éxito!')
    return reverse_lazy('request:mhouse')
  
  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)
    
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Nueva casa médica'
    return context

class MedicalHouseUpdateView(UpdateView):
  model = MedicalHouse
  form_class = MedicalHouseForm
  template_name = "mhouse/edit.html"

  def get_success_url(self):
    messages.success(self.request, '¡Registro editado con éxito!')
    return reverse_lazy('request:mhouse')
  
  def dispatch(self, request, *args, **kwargs):
    return super().dispatch(request, *args, **kwargs)
    
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["title"] = 'Editar registro de casa médica'
    return context

request/templates/entry/create.html
{% extends 'admin.html' %}
{% load static %}

{% block content %}
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">{{ title }}</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'authentication:dashboard' %}">Tablero</a></li>
            <li class="breadcrumb-item"><a href="{% url 'request:prerequest' %}">Pre solicitudes</a></li>
            <li class="breadcrumb-item active">{{ title }}</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
  <section class="content">
    <div class="container-fluid">
      <form action="{% url 'request:entry_create' %}" method="post">
        {% csrf_token %}
        <div class="row">
          <section class="col-md-12">
            <div class="card card-outline card-success">
              <div class="card-header">
                <h3 class="card-title">INGRESO</h3>
              </div>
              <div class="card-body">
                <div class="row">
                  {% for field in form.visible_fields %}
                  {% if field.name == 'comment' %}
                    <div class="col-md-12">
                      <div class="form-group">
                        <label for="{{ field.name }}">{{ field.label }}</label>
                        {{ field }}
                      </div>
                    </div>
                  {% else %}
                    <div class="col-md-4">
                      <div class="form-group">
                        <label for="{{ field.name }}">{{ field.label }}</label>
                        {{ field }}
                      </div>
                    </div>
                  {% endif %}
                  {% endfor %}
                </div>
              </div>
            </div>
          </section>
          <section class="col-md-12">
            <div class="card card-outline card-info">
              <div class="card-header">
                <h5 class="card-title">DETALLE DE INGRESO</h5>
              </div>
              <div class="card-body" id="detail_entry">
                <div class="form-group">
                  <label for="lst_material">Materiales</label>
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-briefcase-medical"></i></span>
                    </div>
                    <input type="text" name="lst_material" id="lst_material" class="form-control lst-material" style="width:90%" autocomplete="off">
                  </div>
                </div>
                <table id="det_entry" class="table table-bordered table-striped" style="width:100%;">
                  <thead>
                    <tr>
                      <th width="10%">opciones</th>
                      <th>Material</th>
                      <th width="10%">Precio de compra</th>
                      <th width="10%">Cantidad</th>
                      <th width="10%">Subtotal</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th colspan="4" style="text-align: right;">TOTAL MATERIALES</th>
                      <th>
                        <input type="number" id="total" style="text-align: center;" class="form-control total_entry" value="0" readonly>
                      </th>
                    </tr>
                  </tfoot>
                </table>
              </div>
              <div class="card-footer" id="actions">
                <button type="button" class="btn btn-outline-danger"><i class="fas fa-times"></i> CANCELAR </button>
                <button type="submit" class="btn btn-outline-success float-right"><i class="fas fa-check"></i> GUARDAR </button>
              </div>
            </div>
          </section>
        </div>
      </form>
    </div>
  </section>
{% endblock content %}

{% block scripts %}
  <script src="{% static 'assets/js/resources/entry.js' %}"></script>
{% endblock %}

request/templates/entry/inactive.html
<div class="modal-dialog" style="min-height: calc(100vh - 60px);display: flex;flex-direction: column;
justify-content: center;overflow: auto;@media(max-width: 768px) {  min-height: calc(100vh - 20px);}">
  <div class="modal-content">
    <form id="formOrderDelete" action="{% url 'request:entry_inactive' object.id %}" method="post">
      <div class="modal-body" style="text-align: center;">
        <div class="swal2-icon swal2-warning swal2-icon-show" style="display: flex;">
          <div class="swal2-icon-content">!</div>
        </div>
        <h2 class="swal2-title">{{ title }}</h2>
        {% csrf_token %}
        <div class="swal2-html-container"> ¿Estas seguro de inactivar el ingreso ?</div>
        <!-- <div class="col-md-12">
          <div class="form-group">
            <label>Justificación</label>
            <input type="text" id="abort_comment" name="abort_comment" required class="form-control"/>
          </div>
        </div> -->
        <div class="swal2-actions" style="display: flex;">
          <button type="submit" class="swal2-confirm swal2-styled" style="display: inline-block;">Si, Anular</button>
          <button type="button" class="swal2-cancel swal2-styled swal2-default-outline" style="display: inline-block; background-color: rgb(221, 51, 51);" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </form>
  </div>
</div>

request/templates/entry/index.html
{% extends 'admin.html' %}

{% block content %}
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0" id="titleview">Ingreso de materiales</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'authentication:dashboard' %}">Tablero</a></li>
            <li class="breadcrumb-item active">Ingreso de materiales</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Listado de ingresos</h5>
              <a type="button" class="btn btn-primary float-right" href="{% url 'request:entry_create' %}"><i class="fas fa-plus"></i> Nuevo</a>
            </div>
            <div class="card-body">
              <table id="lists" class="table table-bordered table-hover table-striped" style="width:100%">
                <thead>
                  <tr>
                    <th>Código</th>
                    <th>Fecha de ingreso</th>
                    <th>Fecha de adjudicación</th>
                    <th>NOG</th>
                    <th>Casa médica</th>
                    <th>SIAF</th>
                    <th>PPR</th>
                    <th>Estado</th>
                    <th>Stock</th>
                    <th>Opciones</th>
                  </tr>
                </thead>
                <tbody>
                  {% for item in object_list %}
                    <tr>
                      <td>{{ item.entry_detail.entry.code }}</td>
                      <td>{{ item.entry_detail.entry.date }}</td>
                      <td>{{ item.entry_detail.entry.date_award }}</td>
                      <td>{{ item.entry_detail.entry.nog }}</td>
                      <td>{{ item.entry_detail.entry.house.name }}</td>
                      <td>{{ item.entry_detail.entry.siaf }}</td>
                      <td>{{ item.entry_detail.entry.ppr }}</td>
                      <td>{{ item.entry_detail.entry.status.name }}</td>
                      <td>{{ item.stock }}</td>
                      <td class="text-center">
                        <button class="btn btn-info"><i class="fas fa-eye"></i></button>
                        {% if item.entry_detail.entry.status.id != 17 %}
                          <button class="btn btn-danger" onclick="openModal(`{% url 'request:entry_inactive' item.entry_detail.entry.pk %}`)"><i class="fas fa-trash"></i></button>
                        {% endif %}
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}